server_lookup = {
    "Aegwynn": "aegwynn",
    "Aerie Peak": "aerie-peak",
    "Agamaggan": "agamaggan",
    "Aggramar": "aggramar",
    "Akama": "akama",
    "Alexstrasza": "alexstrasza",
    "Alleria": "alleria",
    "Altar of Storms": "altar-of-storms",
    "Alterac Mountains": "alterac-mountains",
    "Aman'Thul": "amanthul",
    "Andorhal": "andorhal",
    "Anetheron": "anetheron",
    "Antonidas": "antonidas",
    "Anub'arak": "anubarak",
    "Anvilmar": "anvilmar",
    "Arathor": "arathor",
    "Archimonde": "archimonde",
    "Area 52": "area-52",
    "Argent Dawn": "argent-dawn",
    "Arthas": "arthas",
    "Arygos": "arygos",
    "Auchindoun": "auchindoun",
    "Azgalor": "azgalor",
    "Azjol-Nerub": "azjol-nerub",
    "Azralon": "azralon",
    "Azshara": "azshara",
    "Azuremist": "azuremist",
    "Baelgun": "baelgun",
    "Balnazzar": "balnazzar",
    "Barthilas": "barthilas",
    "Black Dragonflight": "black-dragonflight",
    "Blackhand": "blackhand",
    "Blackrock": "blackrock",
    "Blackwater Raiders": "blackwater-raiders",
    "Blackwing Lair": "blackwing-lair",
    "Bladefist": "bladefist",
    "Blade's Edge": "blades-edge",
    "Bleeding Hollow": "bleeding-hollow",
    "Blood Furnace": "blood-furnace",
    "Bloodhoof": "bloodhoof",
    "Bloodscalp": "bloodscalp",
    "Bonechewer": "bonechewer",
    "Borean Tundra": "borean-tundra",
    "Boulderfist": "boulderfist",
    "Burning Blade": "burning-blade",
    "Burning Legion": "burning-legion",
    "Caelestrasz": "caelestrasz",
    "Cairne": "cairne",
    "Cenarion Circle": "cenarion-circle",
    "Cenarius": "cenarius",
    "Cho'gall": "chogall",
    "Chromaggus": "chromaggus",
    "Coilfang": "coilfang",
    "Crushridge": "crushridge",
    "Daggerspine": "daggerspine",
    "Dalaran": "dalaran",
    "Dalvengyr": "dalvengyr",
    "Dark Iron": "dark-iron",
    "Darkspear": "darkspear",
    "Dath'Remar": "dathremar",
    "Dawnbringer": "dawnbringer",
    "Deathwing": "deathwing",
    "Demon Soul": "demon-soul",
    "Dentarg": "dentarg",
    "Destromath": "destromath",
    "Dethecus": "dethecus",
    "Detheroc": "detheroc",
    "Doomhammer": "doomhammer",
    "Draenor": "draenor",
    "Dragonblight": "dragonblight",
    "Dragonmaw": "dragonmaw",
    "Draka": "draka",
    "Drakkari": "drakkari",
    "Drak'Tharon": "draktharon",
    "Drak'thul": "drakthul",
    "Dreadmaul": "dreadmaul",
    "Drenden": "drenden",
    "Dunemaul": "dunemaul",
    "Durotan": "durotan",
    "Duskwood": "duskwood",
    "Earthen Ring": "earthen-ring",
    "Echo Isles": "echo-isles",
    "Eitrigg": "eitrigg",
    "Eldre'Thalas": "eldrethalas",
    "Elune": "elune",
    "Emerald Dream": "emerald-dream",
    "Eonar": "eonar",
    "Eredar": "eredar",
    "Executus": "executus",
    "Exodar": "exodar",
    "Farstriders": "farstriders",
    "Feathermoon": "feathermoon",
    "Fenris": "fenris",
    "Firetree": "firetree",
    "Fizzcrank": "fizzcrank",
    "Frostmane": "frostmane",
    "Frostmourne": "frostmourne",
    "Frostwolf": "frostwolf",
    "Galakrond": "galakrond",
    "Gallywix": "gallywix",
    "Garithos": "garithos",
    "Garona": "garona",
    "Garrosh": "garrosh",
    "Ghostlands": "ghostlands",
    "Gilneas": "gilneas",
    "Gnomeregan": "gnomeregan",
    "Goldrinn": "goldrinn",
    "Gorefiend": "gorefiend",
    "Gorgonnash": "gorgonnash",
    "Greymane": "greymane",
    "Grizzly Hills": "grizzly-hills",
    "Gul'dan": "guldan",
    "Gundrak": "gundrak",
    "Gurubashi": "gurubashi",
    "Hakkar": "hakkar",
    "Haomarush": "haomarush",
    "Hellscream": "hellscream",
    "Hydraxis": "hydraxis",
    "Hyjal": "hyjal",
    "Icecrown": "icecrown",
    "Illidan": "illidan",
    "Jaedenar": "jaedenar",
    "Jubei'Thos": "jubeithos",
    "Kael'thas": "kaelthas",
    "Kalecgos": "kalecgos",
    "Kargath": "kargath",
    "Kel'Thuzad": "kelthuzad",
    "Khadgar": "khadgar",
    "Khaz Modan": "khaz-modan",
    "Khaz'goroth": "khazgoroth",
    "Kil'Jaeden": "kiljaeden",
    "Kilrogg": "kilrogg",
    "Kirin Tor": "kirin-tor",
    "Korgath": "korgath",
    "Korialstrasz": "korialstrasz",
    "Kul Tiras": "kul-tiras",
    "Laughing Skull": "laughing-skull",
    "Lethon": "lethon",
    "Lightbringer": "lightbringer",
    "Lightninghoof": "lightninghoof",
    "Lightning's Blade": "lightnings-blade",
    "Llane": "llane",
    "Lothar": "lothar",
    "Madoran": "madoran",
    "Maelstrom": "maelstrom",
    "Magtheridon": "magtheridon",
    "Maiev": "maiev",
    "Malfurion": "malfurion",
    "Mal'Ganis": "malganis",
    "Malorne": "malorne",
    "Malygos": "malygos",
    "Mannoroth": "mannoroth",
    "Medivh": "medivh",
    "Misha": "misha",
    "Mok'Nathal": "moknathal",
    "Moon Guard": "moon-guard",
    "Moonrunner": "moonrunner",
    "Mug'thol": "mugthol",
    "Muradin": "muradin",
    "Nagrand": "nagrand",
    "Nathrezim": "nathrezim",
    "Nazgrel": "nazgrel",
    "Nazjatar": "nazjatar",
    "Nemesis": "nemesis",
    "Ner'zhul": "nerzhul",
    "Nesingwary": "nesingwary",
    "Nordrassil": "nordrassil",
    "Norgannon": "norgannon",
    "Onyxia": "onyxia",
    "Perenolde": "perenolde",
    "Proudmoore": "proudmoore",
    "Quel'Dorei": "queldorei",
    "Quel'Thalas": "quelthalas",
    "Ragnaros": "ragnaros",
    "Ravencrest": "ravencrest",
    "Ravenholdt": "ravenholdt",
    "Rexxar": "rexxar",
    "Rivendare": "rivendare",
    "Runetotem": "runetotem",
    "Sargeras": "sargeras",
    "Saurfang": "saurfang",
    "Scarlet Crusade": "scarlet-crusade",
    "Scilla": "scilla",
    "Sen'Jin": "senjin",
    "Sentinels": "sentinels",
    "Shadow Council": "shadow-council",
    "Shadowmoon": "shadowmoon",
    "Shadowsong": "shadowsong",
    "Shandris": "shandris",
    "Shattered Halls": "shattered-halls",
    "Shattered Hand": "shattered-hand",
    "Shu'halo": "shuhalo",
    "Silver Hand": "silver-hand",
    "Silvermoon": "silvermoon",
    "Sisters of Elune": "sisters-of-elune",
    "Skullcrusher": "skullcrusher",
    "Skywall": "skywall",
    "Smolderthorn": "smolderthorn",
    "Spinebreaker": "spinebreaker",
    "Spirestone": "spirestone",
    "Staghelm": "staghelm",
    "Steamwheedle Cartel": "steamwheedle-cartel",
    "Stonemaul": "stonemaul",
    "Stormrage": "stormrage",
    "Stormreaver": "stormreaver",
    "Stormscale": "stormscale",
    "Suramar": "suramar",
    "Tanaris": "tanaris",
    "Terenas": "terenas",
    "Terokkar": "terokkar",
    "Thaurissan": "thaurissan",
    "The Forgotten Coast": "the-forgotten-coast",
    "The Scryers": "the-scryers",
    "The Underbog": "the-underbog",
    "The Venture Co": "the-venture-co",
    "Thorium Brotherhood": "thorium-brotherhood",
    "Thrall": "thrall",
    "Thunderhorn": "thunderhorn",
    "Thunderlord": "thunderlord",
    "Tichondrius": "tichondrius",
    "Tol Barad": "tol-barad",
    "Tortheldrin": "tortheldrin",
    "Trollbane": "trollbane",
    "Turalyon": "turalyon",
    "Twisting Nether": "twisting-nether",
    "Uldaman": "uldaman",
    "Uldum": "uldum",
    "Undermine": "undermine",
    "Ursin": "ursin",
    "Uther": "uther",
    "Vashj": "vashj",
    "Vek'nilash": "veknilash",
    "Velen": "velen",
    "Warsong": "warsong",
    "Whisperwind": "whisperwind",
    "Wildhammer": "wildhammer",
    "Windrunner": "windrunner",
    "Winterhoof": "winterhoof",
    "Wyrmrest Accord": "wyrmrest-accord",
    "Ysera": "ysera",
    "Ysondre": "ysondre",
    "Zangarmarsh": "zangarmarsh",
    "Zul'jin": "zuljin",
    "Zuluhed": "zuluhed"
}
