name: Manual Docker Build

on:
  workflow_dispatch:
    inputs:
      dockerfile_path:
        description: 'Path to Dockerfile'
        required: false
        default: './Dockerfile'
        type: string
      image_name:
        description: 'Docker image name'
        required: false
        default: 'dnd-bot'
        type: string
      build_context:
        description: 'Build context path'
        required: false
        default: '.'
        type: string

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.build_context }}
        file: ${{ inputs.dockerfile_path }}
        push: false
        tags: ${{ inputs.image_name }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Display image info
      run: |
        echo "Docker image built successfully!"
        echo "Image name: ${{ inputs.image_name }}:${{ github.sha }}"
        docker images | grep ${{ inputs.image_name }} || echo "Image not found in local registry"